import './settings/DateInfo.js';
import './settings/DarkMode.js';
import './settings/MenuSettings.js';
import './modules/TaskModel.js';
import './utils/EventListeners.js';
import './components/TaskOptions.js';
import './components/Tasks.js';
import './components/TaskEditForm.js';
import './modules/Register.js';
